#Librerias
install.packages("tidyverse")
library(tidyverse)
install.packages("janitor")
library(janitor)

#Importar csv
listado_de_estaciones_con_servicio_de_atendo <- read_delim("Cosas de estudiar/Cursos/Programación/Coursera/Google Data Analyst/Proyecto final/datos/csv/listado-de-estaciones-con-servicio-de-atendo.csv", delim = ";", trim_ws = TRUE, col_types = cols(`Codigo de Estación` = col_integer()))
clean_names(listado_de_estaciones_con_servicio_de_atendo)
listado_de_estaciones_ave_ld_md <- read_delim("Cosas de estudiar/Cursos/Programación/Coursera/Google Data Analyst/Proyecto final/datos/csv/listado_completo_av_ld_md.csv", delim = ";", trim_ws = TRUE, col_types = cols(`CÓDIGO` = col_integer()))
clean_names(listado_de_estaciones_ave_ld_md)
estaciones <- read_delim("Cosas de estudiar/Cursos/Programación/Coursera/Google Data Analyst/Proyecto final/datos/csv/estaciones.csv", delim = ";", trim_ws = TRUE, col_types = cols(`CODIGO` = col_integer()))
clean_names(estaciones)
distribucion_por_dicapacidad <- read_delim("Cosas de estudiar/Cursos/Programación/Coursera/Google Data Analyst/Proyecto final/datos/csv/distribucion-de-las-asistencias-por-tipo-de-discapacidad.csv", delim = ";", col_types = cols(`Persona mayor` = col_number(), `Persona con carrito de niño` = col_number(), `PMR miembros superiores/inferiores` = col_number(), Embarazadas = col_number(), `Discapacidad intelectual` = col_number(), `Discapacidad auditiva` = col_number(), `Dicapacidad visual` = col_number(), `Silla en plaza regular` = col_number(), `Silla en plaza H` = col_number(), `Personas con sordoceguera` = col_number(), `Otros PMR` = col_number()), locale = locale(decimal_mark = ","), trim_ws = TRUE)
clean_names(distribucion_por_dicapacidad)
indicadores_de_calidad_osp <- read_delim("Cosas de estudiar/Cursos/Programación/Coursera/Google Data Analyst/Proyecto final/datos/csv/indicadores-de-calidad-osp.csv", delim = ";", locale = locale(decimal_mark = ","), trim_ws = TRUE)
clean_names(indicadores_de_calidad_osp)
indicadores_de_calidad_sc <- read_delim("Cosas de estudiar/Cursos/Programación/Coursera/Google Data Analyst/Proyecto final/datos/csv/indicadores-de-calidad-servicios-comerciales.csv", delim = ";", locale = locale(decimal_mark = ","), trim_ws = TRUE)
clean_names(indicadores_de_calidad_sc)
numero_de_asistencias <- read_delim("Cosas de estudiar/Cursos/Programación/Coursera/Google Data Analyst/Proyecto final/datos/csv/numero-de-asistencias-del-servicio-atendo.csv", delim = ";", trim_ws = TRUE)
clean_names(numero_de_asistencias)
numero_de_empleados <- read_delim("Cosas de estudiar/Cursos/Programación/Coursera/Google Data Analyst/Proyecto final/datos/csv/numero-de-empleados.csv", delim = ";", trim_ws = TRUE)
clean_names(numero_de_empleados)
indicadores_de_calidad_sc <- read_delim("Cosas de estudiar/Cursos/Programación/Coursera/Google Data Analyst/Proyecto final/datos/csv/indicadores-de-calidad-servicios-comerciales.csv", delim = ";", locale = locale(decimal_mark = ","), trim_ws = TRUE)
clean_names(indicadores_de_calidad_sc)
indicadores_economicos <- read_delim("Cosas de estudiar/Cursos/Programación/Coursera/Google Data Analyst/Proyecto final/datos/csv/principales-indicadores-economicos.csv", delim = ";", locale = locale(decimal_mark = ",", grouping_mark = "."), trim_ws = TRUE)
clean_names(indicadores_economicos)
indicadores_sociales <- read_delim("Cosas de estudiar/Cursos/Programación/Coursera/Google Data Analyst/Proyecto final/datos/csv/principales-indicadores-sociales.csv", delim = ";", locale = locale(decimal_mark = ",", grouping_mark = "."), trim_ws = TRUE)
clean_names(indicadores_sociales)